### ISSUE TITLE
@Body pojo issue

### ISSUE THREAD

**Issue by miomao656** [aurae/retrofit-logansquare#11]
this is my service 

```
@POST("documents")
    Observable<DocumentsRootResponse> getDocuments(@Body DocumentRequest documentRequest);
```

and i have pojo DocumentRequest

```
@JsonObject
public class DocumentRequest {

    @JsonField
    public String action;

    @JsonField
    public Params params;

}
```

Params pojo

```
@JsonObject
public class Params {

    @JsonField
    public Query query;

    @JsonField
    public Filter filter;

    @JsonField
    public Named named;

    @JsonField
    public Fields fields;

    @JsonField
    public long offset;

    @JsonField
    public long rows;

    @JsonField
    public Sort sort;

    @JsonField
    public Facet facet;

}
```

and i use only action and params in DocumentRequest and offset and rows from Params, other fields are not used

i get this exception 

```
W/System.err: com.bluelinelabs.logansquare.NoSuchMapperException: Class data.net.restresponses.documentResponse.DocumentsRootResponse could not be mapped to a JSON object. Perhaps it hasn't been annotated with @JsonObject?
W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.mapperFor(LoganSquare.java:304)
W/System.err:     at com.bluelinelabs.logansquare.LoganSquare.parse(LoganSquare.java:69)
W/System.err:     at com.github.aurae.retrofit2.LoganSquareResponseBodyConverter.convert(LoganSquareResponseBodyConverter.java:28)
W/System.err:     at com.github.aurae.retrofit2.LoganSquareResponseBodyConverter.convert(LoganSquareResponseBodyConverter.java:14)
W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:213)
W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:177)
W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable$2.call(Observable.java:162)
W/System.err:     at rx.Observable$2.call(Observable.java:154)
W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
W/System.err:     at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

```

**Comment by aurae** [comment]
Could you share your `DocumentsRootResponse` class as well?

**Comment by miomao656** [comment]
@aurae my bad, i forgot to annotate DocumentsRootResponse, i was reading the class name wrong in the exception, it works now, tnx :+1:
