### ISSUE TITLE
Dex error when LoganSquareConverterFactory is added to a Retrofit.Builder

### ISSUE THREAD

**Issue by jbarr21** [aurae/retrofit-logansquare#2]
I copied all of the source files into my application and successfully used the `LoganSquareConverterFactory`, but when I use the version from the jCenter artifact, I get a Dex error. I have source & target compatibility set to 1.7 and tried with both the 1.7 and 1.8 JDK's.

gradle android plugin: 1.3.1
ANDROID_COMPILE_SDK=23
ANDROID_BUILD_TOOLS=23.0.1
ANDROID_MIN_SDK=16
ANDROID_TARGET_SDK=22

error:
```
processing com/squareup/leakcanary/internal/LeakCanaryInternals$1.class...
processing com/squareup/leakcanary/internal/LeakCanaryInternals.class...
processing com/squareup/leakcanary/internal/LeakCanaryUi.class...
processing com/squareup/leakcanary/internal/MoreDetailsView.class...
processing com/github/aurae/retrofit/LoganSquareConverterFactory.class...

21:27:49.282 [ERROR] [org.gradle.api.Project] Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : java.lang.RuntimeException: Exception parsing classes
Unknown source file :   at com.android.dx.command.dexer.Main.processClass(Main.java:752)
Unknown source file :   at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
Unknown source file :   at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
Unknown source file :   at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Unknown source file :   at com.android.dx.command.dexer.Main.processOne(Main.java:672)
Unknown source file :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)
Unknown source file : Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Unknown source file :   at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
Unknown source file :   at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
Unknown source file :   at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
Unknown source file :   at com.android.dx.command.dexer.Main.processClass(Main.java:749)
Unknown source file :   ... 12 more
Unknown source file : 1 error; aborting

```

**Comment by aurae** [comment]
Hey! Thanks for your report. The issue might be related to me compiling the artifact on a Java 8 environment. Unfortunately, I'm on vacation at the moment, but I will attend to this problem right after I get back!

**Comment by jbaginski** [comment]
the same here :)

**Comment by adnan-SM** [comment]
Same here, can't use it

**Comment by jbarr21** [comment]
Adding:
```
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
```
to the build.gradle after the plugins are applied and before the dependencies section looks to resolve the issue.

**Comment by aurae** [comment]
This seems like an acceptable quick fix as long as you're not using Retrolambda, thanks for the input! I will fix the issue immediately after getting back to my workstation.

**Comment by aurae** [comment]
I have re-compiled and uploaded the 1.0.0 release using the JDK 7 so that this shouldn't cause any further issues.

**Comment by NikoYuwono** [comment]
Hello, it's still happened on me. Any idea why? I'm using RetroLambda so I'm targeting Java 8.   
The error is

```
Error:Execution failed for task ':app:preDexInternalDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

**Comment by aurae** [comment]
Given the log portion you provided, this error could mean a lot of things. Is there any more output? Try invoking your Gradle task with `--stacktrace`!
